apiVersion: v1
kind: Service
metadata:
  name: my-service-broker
spec:
  selector:
    app: myappbroker
  type: LoadBalancer  
  ports:
  - port: 1883
    targetPort: 1883
    nodePort: 30005